// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeTool() (Tool, error) {
	createForTest := NewCreateFortest()
	migtest := NewMigtest()
	tool := NewTool(createForTest, migtest)
	return tool, nil
}
