// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/shared/configs"
)

// Injectors from wire.go:

func InitializeAppReplication() (AppReplication, error) {
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	replicationState, err := NewReplicationState()
	if err != nil {
		return nil, err
	}
	getReplication := NewReplication(appConfig, replicationState)
	startFunc := NewStartFunc(getReplication)
	backfillFunc := NewBackfillFunc(getReplication, replicationState)
	appReplication := NewAppReplication(startFunc, backfillFunc)
	return appReplication, nil
}
